- hosts: localhost
  tasks:
    - package:
        name: "docker-ce"
        state: present
    - service:
        name: "docker"
        state: started
        enabled: yes
    - copy:
           dest: "/root/Desktop/rhel7_5_software_extras/centos-latest.tar"
           src: "/root/Desktop/rhel7_5_software_extras/centos-latest.tar"
    - docker_image: 
       name: 
    - docker_container:
       name: mynewdocker
       image: centos 
       volumes: /tmp/.X11-unix:/tmp/.X11-unix
       interactive: true
       tty: yes

