- hosts: all
  vars_files:
      - vars.yml 
  tasks:
      - name: partition_create
        parted:
          device: "{{ devname }}"
          number: "{{ partno }}"
          state: present
          part_start: "{{ partsize1 }}"
          part_end: "{{ partsize2 }}"
        tags:
          - partition_create
      
      - name: vg_create
        lvg:
          vg: "{{ vgname }}"
          pvs: "{{ pvname }}"
        tags:
          - vg_create            
      
      
                                                 
